### ISSUE TITLE
Missing Aura: Siegebreaker (Fury Warrior talent)

### ISSUE THREAD

**Issue by Ravager1993** [AzeriteTeam/AzeriteUI#18]
hi, I really love the look of the UI , i just have one tiny issue with it, i main Fury Warrior and i got the Seigebreaker Talent and the seigebreaker debuff isn't being tracked on my target, both on the unit frame and name plate.

tbh this is the only reason i have not used this UI in pvp :D
thx in advance

**Comment by goldpaw** [comment]
Talent abilities should've been there, even in our current restrictive filter, so clearly a blunder by yours truly here. I'm working on a much better system right now, and that will hopefully solve a LOT of issues without the need for all our black- and whitelists. I'll ofc update those too! ;)

Closing this, since it's actually covered under what we're talking about in isssue #8  now! :)
