### ISSUE TITLE
Better MBB (MinimapButtonBag) support!

### ISSUE THREAD

**Issue by yndrelbosch** [AzeriteTeam/AzeriteUI#3]
**Is your feature request related to a problem? Please describe.**
It is really frustrating dealing with minimap buttons as is, because half of them get hidden behind the minimap, or are directly on the minimap, or... yeah.

**Describe the solution you'd like**
A simple and easy solution would be to add a sort of minimap button bag style of feature (MBB is an out of date mod), basically, a single minimap button correctly placed on the minimap that automatically collects and sorts the minimap buttons, and will open when clicked to display them.

**Describe alternatives you've considered**
I honestly don't know of any other methods, though I'm sure there are some, just not as neat and tidy as mine,

**Comment by goldpaw** [comment]
Well our idea wasn't to hide them behind the minimap, it was to hide them completely. And then add some integrated support for MBB for those that feel they must have those buttons. Because MBB represents a single button. 

Adding buttons to the minimap is a bad way for addons to add functionality, because it's a neverending rabbit hole. Not only is there no integrated way in WoW to add these buttons, there is just a certain amount of space around the minimap to add these things. So every addon tend to do it different, meaning adding support for them all is a full-time in itself, which is why MBB is a good alternative. 

I think MBB still works, right? :o 
https://www.curseforge.com/wow/addons/mbb

So if some are still showing but partly covered, I'd rather modify the code to hide them all, not show them better. 

Anyway, we never did get around to adding that proper MBB support, but I'll see if I can't get it in there in one of the next updates. I've renamed this issue to indicate what I'll be adding! :)

**Comment by yndrelbosch** [comment]
When I installed MBB it didn't pull in the minimap buttons like it should have, and the buttons were not hidden at all, as you say they should be.

**Comment by goldpaw** [comment]
MBB supported fixed in 1.2.131-Release.
