### ISSUE TITLE
feature request: show an indication of rare/elite/enemy player on nameplates

### ISSUE THREAD

**Issue by lotheac** [AzeriteTeam/AzeriteUI#34]
When there are lots of units on screen, it's useful to find the important ones at a glance. Enemy players are already visible via class colors per se, but they can be a little difficult to make out still.

In the default UI I used Interface->Names options to make enemy players even more visible (and to be able to target them by name), but these options have no effect on AzeriteUI nameplates.

**Comment by goldpaw** [comment]
The option to show names in the Names menu, those are just that; names. Not names on the nameplates, but names when nameplates are disabled or out of visual range for those units. There are "hidden" options in WoW still to toggle enemy players and enemy NPCs separately, but you need an addon like AdvancedInterfaceOptions to access them now. Blizzard have removed quite a few options from their menu.  

Making rares and bosses stand more out though, that has been on my todo-list for quite some time now, actually. Usually I would say that in this UI any icons at all are spam on the nameplates, but rares and bosses are kind of special, never many at once, and should be easier to pick out of a crowd. 

Would an icon like the rare/boss badges that are beneath the target portrait be a good indicator for rares/bosses? 

When it comes to players, though, I'm not so sure. There's a lot of players in the world, and for people mostly doing PvP it would mean the indicators would always be there. Which would make it redundant and pretty much spam. For my part, the class coloring alone is enough to separate them clearly from NPCs, as NPCs are always colored by reaction or threat. 

Though on the other hand, a situational PvP badge might be worth considering. Not in PvP instances, because there it's implicit that they're PvP enabled, and there's very few NPCs anyway there. But out in the non-instanced world, possibly on Island expeditions. I'll have to think about it. 

Rares and bosses could need some better indicators, though. Going to get started on that one.

**Comment by lotheac** [comment]
On Sun, Jul 07 2019 09:10:15 -0700, Lars Norberg wrote:
> The option to show names in the Names menu, those are just that; names. Not names on the nameplates, but names when nameplates are disabled or out of visual range for those units.

Those options actually do also affect whether nameplates on non-targeted
units display their name on top as well. I personally enable it for
quest NPCs and enemy players -- essentially the presence of a name on
top of the nameplate signifies to me "this is no ordinary monster".

> Making rares and bosses stand more out though, that has been on my todo-list for quite some time now, actually. Usually I would say that in this UI any icons at all are spam on the nameplates, but rares and bosses are kind of special, never many at once, and should be easier to pick out of a crowd. 
> 
> Would an icon like the rare/boss badges that are beneath the target portrait be a good indicator for rares/bosses? 

Yep, I think so. This is what the Blizzard nameplates does (gold/silver
dragon on the nameplate for rares/elites).

> When it comes to players, though, I'm not so sure. There's a lot of players in the world, and for people mostly doing PvP it would mean the indicators would always be there. Which would make it redundant and pretty much spam. For my part, the class coloring alone is enough to separate them clearly from NPCs, as NPCs are always colored by reaction or threat. 
> 
> Though on the other hand, a situational PvP badge might be worth considering. Not in PvP instances, because there it's implicit that they're PvP enabled, and there's very few NPCs anyway there. But out in the non-instanced world, possibly on Island expeditions. I'll have to think about it. 

Having played a bit with war mode enabled, I was confusing death knights
with hostile and rogues with neutral mobs. I don't know what the correct
answer here is though.

-- 
Lauri Tirkkonen | lotheac @ IRCnet

**Comment by goldpaw** [comment]
I guess the correct answer is for me to not assume we all have the same color balance on our monitors, the same color vision or even play in the same type of lighting. So sometimes some indicators for enemy players might indeed be a good idea after all. 

Death Knight red is tilted slightly towards blue, though, and the rogue color might brigher than the neutral color. Then again, when there's like 40 plates floating all over the place and half of them attacking you, then sitting down and studying subtle color differences might not be exactly possible! :laughing: 

I'm getting more and more convinced we need some better separation for at least world PvP or war mode.

**Comment by goldpaw** [comment]
> Those options actually do also affect whether nameplates on non-targeted units display their name on top as well. I personally enable it for quest NPCs and enemy players -- essentially the presence of a name on top of the nameplate signifies to me "this is no ordinary monster".

Ah, that's new then. Or, well, new for me. Might have been there since Legion for all I know. I haven't been using the new Blizz nameplates. 

About the names and extra info: Me and the actual designer of the UI discussed this some months ago, actually, and were planning to add a "PvP Mode" in our menu. That mode would feature more info of this exact kind. Names on nameplates, more icons, health numbers on the target/currently selected nameplate and such. Basically all the things I wanted to put in there, but he didn't want. So the compromise was to make an optional "more info"-mode. 

Because even with class colors in arena, we still have situations where there are multiple of one class, and then we have to go by names to decide targets, not class. So names in PvP are definitely at some point needed. I'll still argue they're not really needed in PvE, though. Tooltip shows names, and when it comes to quest mobs there's a fairly large yellow circle glowing at their feet if they are objectives of an active quest.

**Comment by lotheac** [comment]
On Sun, Jul 07 2019 09:34:07 -0700, Lars Norberg wrote:
> > Those options actually do also affect whether nameplates on non-targeted units display their name on top as well. I personally enable it for quest NPCs and enemy players -- essentially the presence of a name on top of the nameplate signifies to me "this is no ordinary monster".
> 
> Ah, that's new then. Or, well, new for me. Might have been there since Legion for all I know. I haven't been using the new Blizz nameplates. 

It has indeed been there since Legion :)

> About the names and extra info: Me and the actual designer of the UI discussed this some months ago, actually, and were planning to add a "PvP Mode" in our menu. That mode would feature more info of this exact kind. Names on nameplates, more icons, health numbers on the target/currently selected nameplate and such. Basically all the things I wanted to put in there, but he didn't want. So the compromise was to make an optional "more info"-mode. 
> 
> Because even with class colors in arena, we still have situations where there are multiple of one class, and then we have to go by names to decide targets, not class. So names in PvP are definitely at some point needed. I'll still argue they're not really needed in PvE, though. Tooltip shows names, and when it comes to quest mobs there's a fairly large yellow circle glowing at their feet if they are objectives of an active quest. 

I tend to agree with names on nameplates not really being needed in PvE.
For questing the reduced nameplate distance will allow you to see the
text in the game world anyway if no nameplate is being drawn.

There's one possible exception where a name on a nameplate in PvE can be
useful, and it's *on the currently targeted unit*. It can be quite
useful for example if someone calls out "take the next interrupt from
the shadowcaster without a raid marker on it" - you can instantly
confirm you're not targeting some other type of mob, or switch targets,
without averting your eyes from the middle of the screen.

One more thought on the subject of nameplates: compared to the Blizzard
default, AzeriteUI's are *very tall*, especially when mobs are casting
(the castbar is also quite tall, and the spell name is written below
it). In a big dungeon pull for example, nameplates can cover up the
world and each other up quite significantly (with "Overlapping
Nameplates" enabled). As another anecdote I was fighting a single
monster called 'Mechanical Appendage' in Mechagon earlier, and I could
not see its model at all from behind the nameplate and castbar when it
was casting. This is not to say you should change the design, just
something to consider.

-- 
Lauri Tirkkonen | lotheac @ IRCnet

**Comment by lotheac** [comment]
On Sun, Jul 07 2019 09:34:07 -0700, Lars Norberg wrote:
> About the names and extra info: Me and the actual designer of the UI discussed this some months ago, actually, and were planning to add a "PvP Mode" in our menu. That mode would feature more info of this exact kind. Names on nameplates, more icons, health numbers on the target/currently selected nameplate and such. Basically all the things I wanted to put in there, but he didn't want. So the compromise was to make an optional "more info"-mode. 

Incidentally in my local fork I have also added more space for aura
icons on both the target and player frames, so I suppose I would be a
target user for a 'more info' mode like this. Something related actually
crossed my mind before -- while it makes a lot of sense to filter out
useless auras etc. by default, there may be situations where you
actually want to see every aura, especially on the player character; how
do you click off a buff you don't even know is there?

-- 
Lauri Tirkkonen | lotheac @ IRCnet

**Comment by goldpaw** [comment]
Totally agree with the name on the target nameplate. 

When it comes to auras on the player frame though, I'd say that even though there are situations where you might want to see every single one, there's not situation where you NEED to see every single one. 

Nor can you. We can have 64 buffs and equally many debuffs I believe. The default blizzard buff area next to the minimap shows 32 buffs, 16 debuffs. AzeriteUI's player frame has room for for 8 in total. A whole lot of intelligent filtering is needed to make that one work. 

Also, I have yet to see a situation where much more than 7-8 auras at once actually mattered.

**Comment by goldpaw** [comment]
I mean, I get 5-8 auras without a duration just standing around in Boralus. Then I go into Cat Form and add a ton more. Not to mention a large number of constant procs from Azerite gear. Which in the end makes close to zero difference for combat or playstyle. At least the playstyle of the target audience of this UI. We're really not aiming to please world class raiders here. 

So what does matter then? I'd say anything that directly affects the combat situation. Which is HoTs, DoTs, shields, big DPS cooldowns, stuff like that. And ofc toys and mounts, people will roll me in tar and set me on fire if I don't include a way to see those! :D

**Comment by goldpaw** [comment]
Having all that said, one of the many things on my secret not so little todo list is a tooltip-like frame that just shows ALL the auras at once. Which I did say just now never would happen, but up there I was referring to the constantly visible player frame auras. Not a tooltip-like temporary hover thing. 

Because it is useful to get an overview when preparing for a raid, when studying zone buffs in new areas, and so on. Useful to have the ability to see them. Not to have them there constantly.

**Comment by lotheac** [comment]
On Sun, Jul 07 2019 10:02:57 -0700, Lars Norberg wrote:
> I mean, I get 5-8 auras without a duration just standing around in Boralus. Then I go into Cat Form and add a ton more. Not to mention a large number of constant procs from Azerite gear. Which in the end makes close to zero difference for combat or playstyle. At least the playstyle of the target audience of this UI. We're really not aiming to please world class raiders here. 

Sure. Blacklisting those "always on" buff displays is fine, but...

> So what does matter then? I'd say anything that directly affects the combat situation. Which is HoTs, DoTs, shields, big DPS cooldowns, stuff like that. And ofc toys and mounts, people will roll me in tar and set me on fire if I don't include a way to see those! :D 

It's hard to know before the fact what will affect the combat situation.
For example there may be zone effects that give you a buff with no
duration that you want to know for sure if you are standing in or not,
and whether the monsters are standing in them or not (Shrine of the
Storm / Tidesage Council). So I tend to fall on the side of blacklisting
useless stuff instead of whitelisting useful. As a result I most likely
have useless auras displayed, but I accept the tradeoff.

Out of combat on the other hand, one example off the top of my head:
there is a buff with no duration that is put on the player when solving
the match-3 world quests in Nazjatar. Right clicking that buff off is
the *only way to exit that minigame*, short of completing it. If that
buff gets hidden due to some heuristic, you can get stuck.

-- 
Lauri Tirkkonen | lotheac @ IRCnet

**Comment by goldpaw** [comment]
Mini-game buffs can be whitelisted, even in the current system. 

And there is a whole range of dungeon-specific auras in our aura lists, but not stritctly certain if they've been added to the target- and nameplate filters yet.

**Comment by goldpaw** [comment]
I did get stuck on a Nazjatar item just today, btw. That shell kind of thing that makes you move very fast, but keeps you moving constantly. It had just a 2 minute duration or so, I think, so it wasn't visible out of combat. That was a bummer. 

The new upcoming aura filtering system will take care of that, though.

**Comment by lotheac** [comment]
I think we're in agreement on most counts. I just think that whitelisting auras and hiding everything else is something that requires considerable effort from maintainers of such whitelists -- inevitably there will be some content that has some buff that is really important to show, but the whitelist maintainer is not aware because they haven't done the content (yet). However, I think a mouseover tooltip-like "show me everything" aura frame would go a long way towards working around such issues, also making it easier for whitelist maintainers to discover auras they did not yet know about.

**Comment by goldpaw** [comment]
Seems like a lengthy discussion was going on here. Anyway, closing this as the feature request to show unit rare/elite/boss status on nameplates as well as many other additions is implemented through our KuiNameplates theme instead:
https://www.curseforge.com/wow/addons/kuinameplates-azeriteui
