### ISSUE TITLE
Request action bars toggle

### ISSUE THREAD

**Issue by masterludda** [AzeriteTeam/AzeriteUI#4]
Hi,i would like to request that the action bars could be disabled and enabled via a setting.
For those of us that use Console port,its a great layout for a controller and that plays on a large tv.

Thanks in a advance.

**Comment by goldpaw** [comment]
We're considering adding this as an option for Console Port users. I'll updated this issue when I have more to share!

**Comment by goldpaw** [comment]
As it turns out, there are ways to remove spells from the bars and still have them accessible using ConsolePort's own systems. So seeing how our bars is a very integral part of the UI, we'd rather not have them disabled if it can be worked around or avoided. 

We have several ConsolePort users on our Discord, feel free to stop by and ask how they did their setups! :) 
https://discord.gg/MUSfWXd

**Comment by masterludda** [comment]
I really appreciate it, I understand it's a main focus of your project.

Sent from Yahoo Mail on Android 
 
  On Tue, Mar 26, 2019 at 4:29 AM, Lars Norberg<notifications@github.com> wrote:   
As it turns out, there are ways to remove spells from the bars and still have them accessible using ConsolePort's own systems. So seeing how our bars is a very integral part of the UI, we'd rather not have them disabled if it can be worked around or avoided.

We have several ConsolePort users on our Discord, feel free to stop by and ask how they did their setups! :)
https://discord.gg/MUSfWXd
