### ISSUE TITLE
Remove usage of Blizzard's UIDropDownMenu as it's a known source of headache

### ISSUE THREAD

**Issue by lotheac** [AzeriteTeam/AzeriteUI#44]
As you may remember from previous communication, I'm experimenting with Blizzard_CompactRaidFrames in my AzeriteUI fork. It, however, gets tainted by AzeriteUI.

Steps to reproduce:
1. create a party or get invited to one when in combat. this shows the compact party frames if they're enabled
2. /dump issecurevariable("CompactPartyFrame")
3. observe taint by AzeriteUI

Applying https://github.com/lotheac/AzeriteUI/commit/f97d4462d15ff3b1cf46f621522e358a66e889d4 makes the taint not happen in this case, and group changes are reflected in the compact raid frames while in combat as well. So it looks like UIDropDownMenuTemplate usage in chatwindows.lua is the culprit.

Obviously this is not the correct fix since it disables chat windows' dropdown menus, but I figured I'd report this anyway since UIDropDownMenu taint could easily spread to other places as well.

**Comment by goldpaw** [comment]
Good old Blizzard. Sneeze at their code and taint the universe, even when we don't actually change or modify anything of theirs at all. It's enough to call ToggleDropDownMenu. Known problem, so I'm kind of wondering why I did it in the first place. 

Anyway, this requires a full replacement of the DropDown with a fully recreated non-blizzard one to be fixed. I'll get on it. 

I'll change the label of this to enhancement. Just because I don't acknowledge working around stupid Blizzard coding as a bug fix, but rather think of it as a service to humanity. 
;)

**Comment by goldpaw** [comment]
Found a simpler workaround in 1.2.174-Release. Dropdowns not changed anymore.
